config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # root to: "lists#index"
  resources :lists, only: [ :index, :show, :new, :create, :destroy ] do
    resources :bookmarks, only: [ :new, :create ]
  end
    resources :bookmarks, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy # WE SHOULD HAVE CHECKED THE LOGS IN YOUR SERVER: IT WAS TALKING ABOUT THIS PROBLEM!
  before_action :set_list, only: [:create]


  def create
    #NOW IT'S TIME TO ADD WHAT IS MISSING HERE: CARRY THE RAISE TO THE LINE AFTER @bookmark.save and see what is missing
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      redirect_to list_path(@list), status: :unprocessable_entity
    end
  end
  def destroy
    @bookmark.destroy
    redirect_to bookmarks_path, status: :see_other
  end
 #TODO: SOMETHING IS MISSING HERE: Look at line 2

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
  #TODO: PERMIT
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end
  def new
    @list = List.new
  end
  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/bookmarks/create.html.erb
<%= link_to "Back to Lists", lists_path, class: "btn btn-warning" %>

<div class="p-5">
  <h1 class="pt-5"><%= @list.name %></h1>
  <div class="pt-5">
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.association :movie, collection: Movie.order(:title), prompt: "Select a movie" %>
      <%= f.input :comment, placeholder: "Write a comment" %>
      <%= f.submit "Add Bookmark", class: "btn btn-warning" %>
    <% end %>
  </div>
</div>

app/views/bookmarks/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a movie to your <%= @list.name %> list</h3>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: "Enter a comment about the movie" %>
          <%= f.association :movie, prompt: "Select a movie", input_html: {data: {controller: "tom-select"}} %>
          <%= f.submit class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center p-3">
    <h1>Save any kind of movies</h1>
    <h3 class="typed-js" data-controller="typed-js"></h3>
  </div>
</div>
<div class="container py-5">
  <div class="d-flex align-items-centerjustify-content-between mb-3">
    <h3 class="mb-0">My Lists</h3>
  </div>
  <div class="create-button">
    <%= link_to "Create a movie list", new_list_path, class: "btn btn-warning"%>
  </div>
</div>

<div class="container">
  <div class="lists-grid">
    <% @lists.each do |list| %>
      <div class="list-card-white p-5 rounded">
        <h2><%= link_to list.name, list_path(list), class:"text-decoration-none text-black" %></h2>
        <br>
        <div class="small">
          <%= link_to list_path(list), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="banner">
  <img src="https://images.unsplash.com/photo-1585647347384-2593bc35786b?q=80&w=3270&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D alt=">
</div>
<div class="new-lists p-5">
  <div class="new-list">
    <h1>Create a new <strong>list</strong> !</h1>
    <%= simple_form_for(@list) do |f| %>
      <%= f.input :name %>
      <%# <%= f.input :photo, as: :file %>
      <%= f.submit "Submit", class: "btn btn-warning" %>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<%= link_to "Back to Lists", lists_path, class: "btn btn-warning" %>

<div class="p-5">
  <h1><%= @list.name %></h1>
  <div class="pt-5">
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.association :movie %>
      <%= f.input :comment, placeholder: "Write a comment" %>
      <%= f.button :submit, "Add Bookmark", class: "btn btn-warning" %>
    <% end %>
  </div>

  <h1>Movies in this list</h1>
  <div class="movie-container lists-grid py-5">
    <% @list.movies.each do |movie| %>
      <div class="movie-card">
        <h3><%= movie.title %></h3>
        <p><%= movie.overview %></p>
        <p>Rating: <%= movie.rating %></p>
        <img src="<%= movie.poster_url %>" alt="<%= movie.title %> poster">
      </div>
    <% end %>
  </div>
</div>